# Generated by Django 4.1.5 on 2023-03-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_register_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantroom',
            name='area',
            field=models.TextField(choices=[('Borivali(east)', 'Borivali(east)'), ('Borivali(West)', 'Borivali(west)'), ('Kandivali(east)', 'Kandivali(east)'), ('Kandivali(west)', 'Kandivali(west)'), ('Dahisar(east)', 'Dahisar(east)'), ('Dahisar(West)', 'Dahisar(west)'), ('Miraroad(east)', 'Miraroad(east)'), ('Miraroad(West)', 'Miraroad(west)'), ('Bhaindar(east)', 'Bhaindar(east)'), ('Bhaindar(West)', 'Bhaindar(west)'), ('Naigoan(east)', 'Naigoan(east)'), ('Naigoan(West)', 'Naigoan(west)'), ('Vasairoad(east)', 'Vasairoad(east)'), ('Vasairoad(West)', 'Vasairoad(west)'), ('Nalasopara(east)', 'Nalasopara(east)'), ('Nalasopara(West)', 'Nalasopara(west)'), ('Virar(east)', 'Virar(east)'), ('Virar(West)', 'Virar(west)')], default='Kandivali(East)'),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='city',
            field=models.TextField(choices=[('Mumbai', 'Mumbai')], default='Mumbai'),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='state',
            field=models.TextField(choices=[('Maharashtra', 'Maharashtra')], default='Maharashtra'),
        ),
    ]
