# Generated by Django 4.1.5 on 2023-03-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vacantroom_rent_vacantroom_room_mate_present_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('address', models.TextField()),
                ('state', models.TextField(choices=[('Maharashtra', 'Maharashtra')], default='Maharashtra')),
                ('city', models.TextField(choices=[('Mumbai', 'Mumbai')], default='Mumbai')),
                ('area', models.TextField(choices=[('Borivali(east)', 'Borivali(east)'), ('Borivali(West)', 'Borivali(west)'), ('Kandivali(east)', 'Kandivali(east)'), ('Kandivali(west)', 'Kandivali(west)'), ('Dahisar(east)', 'Dahisar(east)'), ('Dahisar(West)', 'Dahisar(west)'), ('Miraroad(east)', 'Miraroad(east)'), ('Miraroad(West)', 'Miraroad(west)'), ('Bhaindar(east)', 'Bhaindar(east)'), ('Bhaindar(West)', 'Bhaindar(west)'), ('Naigoan(east)', 'Naigoan(east)'), ('Naigoan(West)', 'Naigoan(west)'), ('Vasairoad(east)', 'Vasairoad(east)'), ('Vasairoad(West)', 'Vasairoad(west)'), ('Nalasopara(east)', 'Nalasopara(east)'), ('Nalasopara(West)', 'Nalasopara(west)'), ('Virar(east)', 'Virar(east)'), ('Virar(West)', 'Virar(west)')], default='Kandivali(East)')),
                ('room_mate_present', models.IntegerField()),
                ('room_mate_require', models.IntegerField()),
                ('sellprice', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('lastdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacanthouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('address', models.TextField()),
                ('state', models.TextField(choices=[('Maharashtra', 'Maharashtra')], default='Maharashtra')),
                ('city', models.TextField(choices=[('Mumbai', 'Mumbai')], default='Mumbai')),
                ('area', models.TextField(choices=[('Borivali(east)', 'Borivali(east)'), ('Borivali(West)', 'Borivali(west)'), ('Kandivali(east)', 'Kandivali(east)'), ('Kandivali(west)', 'Kandivali(west)'), ('Dahisar(east)', 'Dahisar(east)'), ('Dahisar(West)', 'Dahisar(west)'), ('Miraroad(east)', 'Miraroad(east)'), ('Miraroad(West)', 'Miraroad(west)'), ('Bhaindar(east)', 'Bhaindar(east)'), ('Bhaindar(West)', 'Bhaindar(west)'), ('Naigoan(east)', 'Naigoan(east)'), ('Naigoan(West)', 'Naigoan(west)'), ('Vasairoad(east)', 'Vasairoad(east)'), ('Vasairoad(West)', 'Vasairoad(west)'), ('Nalasopara(east)', 'Nalasopara(east)'), ('Nalasopara(West)', 'Nalasopara(west)'), ('Virar(east)', 'Virar(east)'), ('Virar(West)', 'Virar(west)')], default='Kandivali(East)')),
                ('room_mate_present', models.IntegerField()),
                ('room_mate_require', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
                ('lastdate', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='vacantroom',
            name='rent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vacantroom',
            name='room_mate_present',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vacantroom',
            name='room_mate_require',
            field=models.IntegerField(),
        ),
    ]
