# Generated by Django 4.1.5 on 2023-03-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sellroom_vacanthouse_alter_vacantroom_rent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacanthouse',
            name='room_mate_present',
        ),
        migrations.RemoveField(
            model_name='vacanthouse',
            name='room_mate_require',
        ),
    ]
