# Generated by Django 4.1.5 on 2023-03-31 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_vacanthouse_room_mate_present_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellroom',
            name='room_mate_present',
        ),
        migrations.RemoveField(
            model_name='sellroom',
            name='room_mate_require',
        ),
    ]
