# Generated by Django 4.1.5 on 2023-04-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_sellroom_room_mate_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacantroom',
            name='name1',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='name10',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='name2',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='name3',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='name4',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='name5',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='name6',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='name7',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='name8',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='name9',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='qualification1',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='qualification10',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='qualification2',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='qualification3',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='qualification4',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='qualification5',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='qualification6',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='qualification7',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='qualification8',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vacantroom',
            name='qualification9',
            field=models.TextField(default=0),
        ),
    ]
