# Generated by Django 4.1.5 on 2023-04-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_vacantroom_name1_vacantroom_name10_vacantroom_name2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacantroom',
            name='room_mate_present',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0),
        ),
        migrations.AlterField(
            model_name='vacantroom',
            name='room_mate_require',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=0),
        ),
    ]
